"""
Remediation Agent — Polls the 'incidents' topic and generates a Kafka Streams
filter to remediate the faulty messages.

SKILL.md (kafka-streams-filter) is read ONCE at startup and injected into the
ADK agent's instruction (not re-read per message). The agent applies the
procedure itself through its tools (read_incident, generate_filter,
deploy_filter) — the Python loop only drives Kafka polling and provides a
deterministic fallback so the demo pipeline never stalls on an LLM outage.

The remediation LLM is OPTIONAL, same principle as the other agents. If
REMEDIATION_LLM_API_KEY is empty, no ADK agent is ever instantiated: every
incident goes straight through the deterministic filter-code template.
"""

import json
import logging
import signal
import time
from datetime import datetime, timezone

from confluent_kafka import Consumer, Producer, KafkaError

from common.config import (
    KAFKA_BOOTSTRAP_SERVERS,
    SKILL_PATH,
    TOPIC_INCIDENTS,
    TOPIC_REPLAY_TASKS,
    TOPIC_AUDIT,
    TOPIC_FACTURATION,
    REMEDIATION_LLM_PROVIDER,
    REMEDIATION_LLM_MODEL,
    REMEDIATION_LLM_API_KEY,
)
from common.adk_factory import AdkAgentRunner
from remediation.prompts import SYSTEM_PROMPT, REMEDIATION_USER_PROMPT

# Logging with [REMEDIATION] prefix
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [REMEDIATION] %(levelname)s %(message)s",
)
logger = logging.getLogger("remediation")

# Signal for graceful shutdown
shutdown_event = False


def handle_sigterm(signum, frame):
    """Handle SIGTERM for graceful shutdown."""
    global shutdown_event
    logger.info("SIGTERM received, shutting down gracefully...")
    shutdown_event = True


signal.signal(signal.SIGTERM, handle_sigterm)
signal.signal(signal.SIGINT, handle_sigterm)


def load_skill_file() -> str:
    """Load the SKILL.md file content for the kafka-streams-filter procedure."""
    try:
        with open(SKILL_PATH, "r", encoding="utf-8") as f:
            content = f.read()
        logger.info(f"SKILL.md loaded from {SKILL_PATH} ({len(content)} chars)")
        return content
    except FileNotFoundError:
        logger.error(f"SKILL.md not found at {SKILL_PATH}")
        return ""
    except Exception as e:
        logger.exception(f"Failed to load SKILL.md: {e}")
        return ""


def generate_filter_code(incident: dict) -> str:
    """
    Deterministic Kafka Streams filter generator, following the
    kafka-streams-filter SKILL.md procedure: identify the faulty field,
    build a filter() topology with a JSON Serde and a dead-letter branch.
    """
    cause = incident.get("cause", "unknown")
    field = "siret" if "siret" in cause else "unknown_field"

    return f"""// Auto-generated by remediation-agent — incident {incident.get("incident_id", "unknown")}
// Cause: {cause} — messages_affected: {incident.get("messages_affected", 0)}
//
// Topology: filters out records with a null/missing '{field}' field from
// '{TOPIC_FACTURATION}', routing rejects to a dead-letter topic.

StreamsBuilder builder = new StreamsBuilder();

Serde<JsonNode> jsonSerde = new JsonSerde();

KStream<String, JsonNode> source = builder.stream(
    "{TOPIC_FACTURATION}",
    Consumed.with(Serdes.String(), jsonSerde)
);

KStream<String, JsonNode>[] branches = source.branch(
    (key, value) -> value.hasNonNull("{field}"),   // valid: '{field}' present and non-null
    (key, value) -> true                            // reject: everything else -> DLT
);

branches[0].to("{TOPIC_FACTURATION}-valid", Produced.with(Serdes.String(), jsonSerde));
branches[1].to("{TOPIC_FACTURATION}-dlt", Produced.with(Serdes.String(), jsonSerde));

KafkaStreams streams = new KafkaStreams(builder.build(), streamsConfig);
streams.start();

// Unit test (TopologyTestDriver): feed one valid + one null-'{field}' record,
// assert the valid record lands on '{TOPIC_FACTURATION}-valid' and the
// null-'{field}' record lands on '{TOPIC_FACTURATION}-dlt'.
"""


def produce_audit_log(producer: Producer, incident: dict, code: str) -> None:
    """Log the generated filter to the 'audit' topic."""
    audit = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "incident_id": incident.get("incident_id"),
        "action": "deploy_filter",
        "filter_code": code,
    }
    producer.produce(
        TOPIC_AUDIT,
        key=str(incident.get("incident_id")),
        value=json.dumps(audit, ensure_ascii=False).encode("utf-8"),
    )
    logger.info(f"Audit log produced for incident {incident.get('incident_id')}")


def produce_replay_task(producer: Producer, incident: dict) -> None:
    """Publish a replay task derived from the incident to 'replay-tasks'."""
    task = {
        "incident_id": incident.get("incident_id"),
        "topic": TOPIC_FACTURATION,
        "filter": "siret is null",
        "count": incident.get("messages_affected", 0),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    producer.produce(
        TOPIC_REPLAY_TASKS,
        key=str(incident.get("incident_id")),
        value=json.dumps(task, ensure_ascii=False).encode("utf-8"),
    )
    logger.info(f"Replay task produced: incident={incident.get('incident_id')} count={task['count']}")


class RemediationTools:
    """Tools exposed to the remediation ADK agent. Tracks side effects for the fallback logic."""

    def __init__(self, producer: Producer):
        self._producer = producer
        self.reset(incident=None)

    def reset(self, incident: dict | None) -> None:
        self.current_incident = incident
        self.filter_generated = False
        self.filter_deployed = False
        self.last_code: str | None = None

    def read_incident(self) -> dict:
        """Return the incident currently being processed (fetched from 'incidents' by the polling loop)."""
        return self.current_incident or {}

    def generate_filter(self, incident_json: str) -> str:
        """Generate the Kafka Streams filter code for the given incident (topology, Serde, DLT). Call exactly once."""
        try:
            incident = json.loads(incident_json) if isinstance(incident_json, str) else incident_json
        except json.JSONDecodeError:
            incident = self.current_incident or {}
        code = generate_filter_code(incident)
        self.last_code = code
        self.filter_generated = True
        logger.info(f"Filter generated for incident {incident.get('incident_id')}")
        return code

    def deploy_filter(self, code: str) -> str:
        """Log the generated filter to 'audit' and publish the corresponding replay task. Call exactly once."""
        incident = self.current_incident or {}
        produce_audit_log(self._producer, incident, code)
        produce_replay_task(self._producer, incident)
        self._producer.flush(timeout=5)
        self.filter_deployed = True
        return "OK: filter deployed"


def main():
    """Main loop — polls 'incidents', delegates remediation to the ADK agent, guarantees a deployed filter."""
    skill_content = load_skill_file()
    if not skill_content:
        logger.warning("SKILL.md is empty or could not be loaded — remediation may be degraded")

    consumer_conf = {
        "bootstrap.servers": KAFKA_BOOTSTRAP_SERVERS,
        "group.id": "remediation-group",
        "auto.offset.reset": "earliest",
        "enable.auto.commit": True,
    }
    consumer = Consumer(consumer_conf)
    consumer.subscribe([TOPIC_INCIDENTS])

    producer = Producer({"bootstrap.servers": KAFKA_BOOTSTRAP_SERVERS})
    tools = RemediationTools(producer)

    agent_runner = None
    if REMEDIATION_LLM_API_KEY:
        instruction = SYSTEM_PROMPT.format(skill_content=skill_content)
        agent_runner = AdkAgentRunner(
            name="remediation-agent",
            description="Génère un filtre Kafka Streams pour remédier aux messages fautifs d'un incident.",
            instruction=instruction,
            tools=[tools.read_incident, tools.generate_filter, tools.deploy_filter],
            provider=REMEDIATION_LLM_PROVIDER,
            model=REMEDIATION_LLM_MODEL,
            api_key=REMEDIATION_LLM_API_KEY,
        )
        logger.info(f"LLM: provider={REMEDIATION_LLM_PROVIDER} model={REMEDIATION_LLM_MODEL}")
    else:
        logger.info("No REMEDIATION_LLM_API_KEY configured — running deterministic filter generation")

    logger.info(f"Remediation agent started. Listening on topic '{TOPIC_INCIDENTS}'")

    try:
        while not shutdown_event:
            msg = consumer.poll(timeout=1.0)

            if msg is None:
                time.sleep(3)
                continue

            if msg.error():
                if msg.error().code() == KafkaError._PARTITION_EOF:
                    time.sleep(3)
                    continue
                logger.error(f"Kafka error: {msg.error()}")
                time.sleep(3)
                continue

            try:
                value = msg.value()
                if value is None:
                    continue
                incident = json.loads(value.decode("utf-8"))
            except (json.JSONDecodeError, UnicodeDecodeError) as e:
                logger.error(f"Failed to parse incident message: {e}")
                continue

            logger.info(
                f"Processing incident: {incident.get('incident_id')} "
                f"cause={incident.get('cause')} messages_affected={incident.get('messages_affected')}"
            )

            tools.reset(incident)
            if agent_runner is not None:
                user_prompt = REMEDIATION_USER_PROMPT.format(
                    incident_id=incident.get("incident_id", ""),
                    consumer_group=incident.get("consumer_group", ""),
                    cause=incident.get("cause", ""),
                    messages_affected=incident.get("messages_affected", 0),
                    timestamp=incident.get("timestamp", ""),
                )
                try:
                    response = agent_runner.run(user_prompt)
                    logger.info(f"Agent response: {response}")
                except Exception as e:
                    logger.error(f"Remediation agent LLM call failed: {e}")

            # Guarantee a filter always gets generated and deployed, even if
            # the LLM failed or forgot to call its tools.
            if not tools.filter_generated:
                logger.warning("No filter generated by the agent — using deterministic template")
                tools.generate_filter(json.dumps(incident, ensure_ascii=False))
            if not tools.filter_deployed:
                tools.deploy_filter(tools.last_code)

            time.sleep(3)

    except Exception as e:
        logger.exception(f"Fatal error in remediation loop: {e}")
    finally:
        logger.info("Closing remediation agent...")
        consumer.close()
        producer.flush(timeout=10)
        logger.info("Remediation agent stopped.")


if __name__ == "__main__":
    main()
